/**
 * Bundles skill/ into a TypeScript module at build time.
 *
 * Cloudflare Workers has no filesystem at runtime, so the skill cannot be read
 * with fs when deployed. Embedding it keeps the repo as the single source of
 * truth while producing something Workers can actually serve.
 *
 * Generated output is git-ignored: the skill lives in skill/, never here.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const skillDir = join(here, "..", "..", "plugins", "gp-01-onboarding-offboarding", "skills", "gp-01-onboarding-offboarding");
const outFile = join(here, "..", "src", "lib", "skill.generated.ts");

const FILES = [
  "SKILL.md",
  "references/connector-map.md",
  "references/approval-gates.md",
  "references/register-schema.md",
  "assets/welcome-email-template.md",
  "assets/completion-report-template.md",
];

const entries = FILES.map((rel) => {
  let content = "";
  try {
    content = readFileSync(join(skillDir, rel), "utf8");
  } catch {
    console.warn(`[embed-skill] missing, skipped: ${rel}`);
    return null;
  }
  return `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`;
}).filter(Boolean);

if (!entries.length) {
  console.error("[embed-skill] no skill files found — is skill/ present?");
  process.exit(1);
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `// GENERATED by scripts/embed-skill.mjs — do not edit. Edit skill/ instead.\n` +
    `export const SKILL_FILES: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
  "utf8",
);
console.log(`[embed-skill] embedded ${entries.length} file(s) from skill/`);
